// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrZFQJoQ2lRNe13_4TKIC1_agFf9AIKE',
    appId: '1:374121484664:web:eb807c0db3a594419eb88d',
    messagingSenderId: '374121484664',
    projectId: 'gear-up-b140f',
    authDomain: 'gear-up-b140f.firebaseapp.com',
    storageBucket: 'gear-up-b140f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNJ-Upn_sqNSrlWEiqwLqZpKbUaYNNoE',
    appId: '1:374121484664:android:a7be106294cfc6cc9eb88d',
    messagingSenderId: '374121484664',
    projectId: 'gear-up-b140f',
    storageBucket: 'gear-up-b140f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVnZ8uX5uxmYbLTUU2oHTJDaaPCnQAaDo',
    appId: '1:374121484664:ios:6ceea3f2b520a7929eb88d',
    messagingSenderId: '374121484664',
    projectId: 'gear-up-b140f',
    storageBucket: 'gear-up-b140f.firebasestorage.app',
    iosBundleId: 'com.example.gearUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVnZ8uX5uxmYbLTUU2oHTJDaaPCnQAaDo',
    appId: '1:374121484664:ios:6ceea3f2b520a7929eb88d',
    messagingSenderId: '374121484664',
    projectId: 'gear-up-b140f',
    storageBucket: 'gear-up-b140f.firebasestorage.app',
    iosBundleId: 'com.example.gearUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrZFQJoQ2lRNe13_4TKIC1_agFf9AIKE',
    appId: '1:374121484664:web:a5e436df3870404b9eb88d',
    messagingSenderId: '374121484664',
    projectId: 'gear-up-b140f',
    authDomain: 'gear-up-b140f.firebaseapp.com',
    storageBucket: 'gear-up-b140f.firebasestorage.app',
  );
}
